// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: anime.sql

package repositories

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAnime = `-- name: CreateAnime :one
insert into "anime" ("name", "anilistId") values ($1, $2) returning id, name, "anilistId"
`

type CreateAnimeParams struct {
	Name      string `json:"name"`
	AnilistId int32  `json:"anilistId"`
}

func (q *Queries) CreateAnime(ctx context.Context, arg CreateAnimeParams) (Anime, error) {
	row := q.db.QueryRow(ctx, createAnime, arg.Name, arg.AnilistId)
	var i Anime
	err := row.Scan(&i.ID, &i.Name, &i.AnilistId)
	return i, err
}

const getAnimeByAnidbId = `-- name: GetAnimeByAnidbId :one
select id, name, "anilistId" from "anime" where "anilistId" = $1 limit 1
`

func (q *Queries) GetAnimeByAnidbId(ctx context.Context, anilistid int32) (Anime, error) {
	row := q.db.QueryRow(ctx, getAnimeByAnidbId, anilistid)
	var i Anime
	err := row.Scan(&i.ID, &i.Name, &i.AnilistId)
	return i, err
}

const updateAnimeNameById = `-- name: UpdateAnimeNameById :one
update "anime" set "name" = $1 where "anime"."id" = $2 returning id, name, "anilistId"
`

type UpdateAnimeNameByIdParams struct {
	Name string      `json:"name"`
	ID   pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateAnimeNameById(ctx context.Context, arg UpdateAnimeNameByIdParams) (Anime, error) {
	row := q.db.QueryRow(ctx, updateAnimeNameById, arg.Name, arg.ID)
	var i Anime
	err := row.Scan(&i.ID, &i.Name, &i.AnilistId)
	return i, err
}
