// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: character.sql

package repositories

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCharacter = `-- name: CreateCharacter :one
insert into
    "character" (
        "image",
        "name",
        "anilistId",
        "birthYear",
        "birthMonth",
        "birthDay",
        "bloodType",
        "age",
        "description",
        "gender"
    )
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) returning id, image, name, "anilistId", "birthYear", "birthMonth", "birthDay", "bloodType", age, description, gender
`

type CreateCharacterParams struct {
	Image       string
	Name        string
	AnilistId   int32
	BirthYear   *int32
	BirthMonth  *int32
	BirthDay    *int32
	BloodType   *string
	Age         *string
	Description *string
	Gender      *string
}

func (q *Queries) CreateCharacter(ctx context.Context, arg CreateCharacterParams) (Character, error) {
	row := q.db.QueryRow(ctx, createCharacter,
		arg.Image,
		arg.Name,
		arg.AnilistId,
		arg.BirthYear,
		arg.BirthMonth,
		arg.BirthDay,
		arg.BloodType,
		arg.Age,
		arg.Description,
		arg.Gender,
	)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.Image,
		&i.Name,
		&i.AnilistId,
		&i.BirthYear,
		&i.BirthMonth,
		&i.BirthDay,
		&i.BloodType,
		&i.Age,
		&i.Description,
		&i.Gender,
	)
	return i, err
}

const getAnimeCharacterRelationByIds = `-- name: GetAnimeCharacterRelationByIds :one
select "animeId", "characterId" from "anime_character" where "animeId" = $1 and "characterId" = $2 limit 1
`

type GetAnimeCharacterRelationByIdsParams struct {
	AnimeId     pgtype.UUID
	CharacterId pgtype.UUID
}

func (q *Queries) GetAnimeCharacterRelationByIds(ctx context.Context, arg GetAnimeCharacterRelationByIdsParams) (AnimeCharacter, error) {
	row := q.db.QueryRow(ctx, getAnimeCharacterRelationByIds, arg.AnimeId, arg.CharacterId)
	var i AnimeCharacter
	err := row.Scan(&i.AnimeId, &i.CharacterId)
	return i, err
}

const getCharacterByAnilistId = `-- name: GetCharacterByAnilistId :one
select id, image, name, "anilistId", "birthYear", "birthMonth", "birthDay", "bloodType", age, description, gender from "character" where "anilistId" = $1 limit 1
`

func (q *Queries) GetCharacterByAnilistId(ctx context.Context, anilistid int32) (Character, error) {
	row := q.db.QueryRow(ctx, getCharacterByAnilistId, anilistid)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.Image,
		&i.Name,
		&i.AnilistId,
		&i.BirthYear,
		&i.BirthMonth,
		&i.BirthDay,
		&i.BloodType,
		&i.Age,
		&i.Description,
		&i.Gender,
	)
	return i, err
}

const linkCharacterToAnime = `-- name: LinkCharacterToAnime :exec
insert into "anime_character" ("animeId", "characterId") values ($1, $2)
`

type LinkCharacterToAnimeParams struct {
	AnimeId     pgtype.UUID
	CharacterId pgtype.UUID
}

func (q *Queries) LinkCharacterToAnime(ctx context.Context, arg LinkCharacterToAnimeParams) error {
	_, err := q.db.Exec(ctx, linkCharacterToAnime, arg.AnimeId, arg.CharacterId)
	return err
}

const updateCharacterById = `-- name: UpdateCharacterById :exec
update "character" set "image" = $1, "name" = $2, "birthYear" = $3, "birthMonth" = $4, "birthDay" = $5, "bloodType" = $6, "age" = $7, "description" = $8, "gender" = $9 where "id" = $10
`

type UpdateCharacterByIdParams struct {
	Image       string
	Name        string
	BirthYear   *int32
	BirthMonth  *int32
	BirthDay    *int32
	BloodType   *string
	Age         *string
	Description *string
	Gender      *string
	ID          pgtype.UUID
}

func (q *Queries) UpdateCharacterById(ctx context.Context, arg UpdateCharacterByIdParams) error {
	_, err := q.db.Exec(ctx, updateCharacterById,
		arg.Image,
		arg.Name,
		arg.BirthYear,
		arg.BirthMonth,
		arg.BirthDay,
		arg.BloodType,
		arg.Age,
		arg.Description,
		arg.Gender,
		arg.ID,
	)
	return err
}
