// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: like.sql

package repositories

import (
	"context"

	"github.com/google/uuid"
)

const checkLikeExists = `-- name: CheckLikeExists :one
select exists (
    select 1 
    from "like"
    where "userId" = $1 and "characterId" = $2
)
`

type CheckLikeExistsParams struct {
	UserId      string    `json:"userId"`
	CharacterId uuid.UUID `json:"characterId"`
}

func (q *Queries) CheckLikeExists(ctx context.Context, arg CheckLikeExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkLikeExists, arg.UserId, arg.CharacterId)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createLike = `-- name: CreateLike :exec
insert into "like" ("userId", "characterId") values ($1, $2)
`

type CreateLikeParams struct {
	UserId      string    `json:"userId"`
	CharacterId uuid.UUID `json:"characterId"`
}

func (q *Queries) CreateLike(ctx context.Context, arg CreateLikeParams) error {
	_, err := q.db.Exec(ctx, createLike, arg.UserId, arg.CharacterId)
	return err
}

const deleteLike = `-- name: DeleteLike :exec
delete from "like" where "userId" = $1 and "characterId" = $2
`

type DeleteLikeParams struct {
	UserId      string    `json:"userId"`
	CharacterId uuid.UUID `json:"characterId"`
}

func (q *Queries) DeleteLike(ctx context.Context, arg DeleteLikeParams) error {
	_, err := q.db.Exec(ctx, deleteLike, arg.UserId, arg.CharacterId)
	return err
}

const getUserLikes = `-- name: GetUserLikes :many
select
  character.id, character.image, character.name, character."anilistId", character."birthYear", character."birthMonth", character."birthDay", character."bloodType", character.age, character.description, character.gender
from
  "like"
  join "character" on "character"."id" = "like"."characterId"
where
  "like"."userId" = $1
`

func (q *Queries) GetUserLikes(ctx context.Context, userid string) ([]Character, error) {
	rows, err := q.db.Query(ctx, getUserLikes, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Character
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.ID,
			&i.Image,
			&i.Name,
			&i.AnilistId,
			&i.BirthYear,
			&i.BirthMonth,
			&i.BirthDay,
			&i.BloodType,
			&i.Age,
			&i.Description,
			&i.Gender,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
