// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: like.sql

package repositories

import (
	"context"

	"github.com/google/uuid"
)

const createLike = `-- name: CreateLike :exec
insert into "like" ("userId", "characterId") values ($1, $2)
`

type CreateLikeParams struct {
	UserId      string    `json:"userId"`
	CharacterId uuid.UUID `json:"characterId"`
}

func (q *Queries) CreateLike(ctx context.Context, arg CreateLikeParams) error {
	_, err := q.db.Exec(ctx, createLike, arg.UserId, arg.CharacterId)
	return err
}

const getUserLikes = `-- name: GetUserLikes :many
select character.id, character.image, character.name, character."anilistId", character."birthYear", character."birthMonth", character."birthDay", character."bloodType", character.age, character.description, character.gender, "anime"."name" as "anime"
from
    "like"
    join "character" on "character"."id" = "like"."characterId"
    join "anime_character" on "anime_character"."characterId" = "character"."id"
    join "anime" on "anime_character"."animeId" = "anime"."id"
where "like"."userId" = $1
`

type GetUserLikesRow struct {
	ID          uuid.UUID `json:"id"`
	Image       string    `json:"image"`
	Name        string    `json:"name"`
	AnilistId   int32     `json:"anilistId"`
	BirthYear   *int32    `json:"birthYear"`
	BirthMonth  *int32    `json:"birthMonth"`
	BirthDay    *int32    `json:"birthDay"`
	BloodType   *string   `json:"bloodType"`
	Age         *string   `json:"age"`
	Description *string   `json:"description"`
	Gender      *string   `json:"gender"`
	Anime       string    `json:"anime"`
}

func (q *Queries) GetUserLikes(ctx context.Context, userid string) ([]GetUserLikesRow, error) {
	rows, err := q.db.Query(ctx, getUserLikes, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserLikesRow
	for rows.Next() {
		var i GetUserLikesRow
		if err := rows.Scan(
			&i.ID,
			&i.Image,
			&i.Name,
			&i.AnilistId,
			&i.BirthYear,
			&i.BirthMonth,
			&i.BirthDay,
			&i.BloodType,
			&i.Age,
			&i.Description,
			&i.Gender,
			&i.Anime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
