// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repositories

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                    string             `json:"id"`
	AccountId             string             `json:"accountId"`
	ProviderId            string             `json:"providerId"`
	UserId                string             `json:"userId"`
	AccessToken           *string            `json:"accessToken"`
	RefreshToken          *string            `json:"refreshToken"`
	IdToken               *string            `json:"idToken"`
	AccessTokenExpiresAt  pgtype.Timestamptz `json:"accessTokenExpiresAt"`
	RefreshTokenExpiresAt pgtype.Timestamptz `json:"refreshTokenExpiresAt"`
	Scope                 *string            `json:"scope"`
	Password              *string            `json:"password"`
	CreatedAt             pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt             pgtype.Timestamptz `json:"updatedAt"`
}

type Anime struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	AnilistId int32     `json:"anilistId"`
}

type AnimeCharacter struct {
	AnimeId     uuid.UUID `json:"animeId"`
	CharacterId uuid.UUID `json:"characterId"`
}

type Character struct {
	ID          uuid.UUID `json:"id"`
	Image       string    `json:"image"`
	Name        string    `json:"name"`
	AnilistId   int32     `json:"anilistId"`
	BirthYear   *int32    `json:"birthYear"`
	BirthMonth  *int32    `json:"birthMonth"`
	BirthDay    *int32    `json:"birthDay"`
	BloodType   *string   `json:"bloodType"`
	Age         *string   `json:"age"`
	Description *string   `json:"description"`
	Gender      *string   `json:"gender"`
}

type Jwk struct {
	ID         string             `json:"id"`
	PublicKey  string             `json:"publicKey"`
	PrivateKey string             `json:"privateKey"`
	CreatedAt  pgtype.Timestamptz `json:"createdAt"`
	ExpiresAt  pgtype.Timestamptz `json:"expiresAt"`
}

type Session struct {
	ID        string             `json:"id"`
	ExpiresAt pgtype.Timestamptz `json:"expiresAt"`
	Token     string             `json:"token"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
	IpAddress *string            `json:"ipAddress"`
	UserAgent *string            `json:"userAgent"`
	UserId    string             `json:"userId"`
}

type User struct {
	ID              string             `json:"id"`
	Name            string             `json:"name"`
	Email           string             `json:"email"`
	EmailVerified   bool               `json:"emailVerified"`
	Image           *string            `json:"image"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt       pgtype.Timestamptz `json:"updatedAt"`
	Username        *string            `json:"username"`
	DisplayUsername *string            `json:"displayUsername"`
}

type Verification struct {
	ID         string             `json:"id"`
	Identifier string             `json:"identifier"`
	Value      string             `json:"value"`
	ExpiresAt  pgtype.Timestamptz `json:"expiresAt"`
	CreatedAt  pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt  pgtype.Timestamptz `json:"updatedAt"`
}

type Vote struct {
	UserId             string             `json:"userId"`
	ForCharacterId     uuid.UUID          `json:"forCharacterId"`
	AgainstCharacterId uuid.UUID          `json:"againstCharacterId"`
	DateTime           pgtype.Timestamptz `json:"dateTime"`
}
