// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repositories

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                    string
	AccountId             string
	ProviderId            string
	UserId                string
	AccessToken           *string
	RefreshToken          *string
	IdToken               *string
	AccessTokenExpiresAt  pgtype.Timestamptz
	RefreshTokenExpiresAt pgtype.Timestamptz
	Scope                 *string
	Password              *string
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

type Anime struct {
	ID        pgtype.UUID
	Name      string
	AnilistId int32
}

type AnimeCharacter struct {
	AnimeId     pgtype.UUID
	CharacterId pgtype.UUID
}

type Character struct {
	ID          pgtype.UUID
	Image       string
	Name        string
	AnilistId   int32
	BirthYear   *int32
	BirthMonth  *int32
	BirthDay    *int32
	BloodType   *string
	Age         *string
	Description *string
	Gender      *string
}

type Jwk struct {
	ID         string
	PublicKey  string
	PrivateKey string
	CreatedAt  pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
}

type Session struct {
	ID        string
	ExpiresAt pgtype.Timestamptz
	Token     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	IpAddress *string
	UserAgent *string
	UserId    string
}

type User struct {
	ID              string
	Name            string
	Email           string
	EmailVerified   bool
	Image           *string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	Username        *string
	DisplayUsername *string
}

type Verification struct {
	ID         string
	Identifier string
	Value      string
	ExpiresAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}
