// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package repositories

import (
	"context"
)

const getUserById = `-- name: GetUserById :one
select id, name, email, "emailVerified", image, "createdAt", "updatedAt", username, "displayUsername" from "user" where "id" = $1 limit 1
`

func (q *Queries) GetUserById(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.DisplayUsername,
	)
	return i, err
}
