// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vote.sql

package repositories

import (
	"context"

	"github.com/google/uuid"
)

const createVote = `-- name: CreateVote :exec
insert into "vote" ("userId", "forCharacterId", "againstCharacterId") values ($1, $2, $3)
`

type CreateVoteParams struct {
	UserId             string    `json:"userId"`
	ForCharacterId     uuid.UUID `json:"forCharacterId"`
	AgainstCharacterId uuid.UUID `json:"againstCharacterId"`
}

func (q *Queries) CreateVote(ctx context.Context, arg CreateVoteParams) error {
	_, err := q.db.Exec(ctx, createVote, arg.UserId, arg.ForCharacterId, arg.AgainstCharacterId)
	return err
}

const getTop100VotedCharacters = `-- name: GetTop100VotedCharacters :many
SELECT "character"."id", "character"."name", "character"."image", COALESCE(
        SUM(
            CASE
                WHEN "vote"."forCharacterId" = "character"."id" THEN 1
                ELSE 0
            END
        ), 0
    ) AS for, COALESCE(
        SUM(
            CASE
                WHEN "vote"."againstCharacterId" = "character"."id" THEN 1
                ELSE 0
            END
        ), 0
    ) AS against, COALESCE(
        SUM(
            CASE
                WHEN "vote"."forCharacterId" = "character"."id" THEN 1
                ELSE 0
            END
        ), 0
    ) - COALESCE(
        SUM(
            CASE
                WHEN "vote"."againstCharacterId" = "character"."id" THEN 1
                ELSE 0
            END
        ), 0
    ) AS score
FROM "character"
    LEFT JOIN "vote" ON "vote"."forCharacterId" = "character".id
    OR "vote"."againstCharacterId" = "character"."id"
GROUP BY
    "character"."id"
ORDER BY score DESC
LIMIT 100
`

type GetTop100VotedCharactersRow struct {
	ID      uuid.UUID   `json:"id"`
	Name    string      `json:"name"`
	Image   string      `json:"image"`
	For     interface{} `json:"for"`
	Against interface{} `json:"against"`
	Score   int32       `json:"score"`
}

func (q *Queries) GetTop100VotedCharacters(ctx context.Context) ([]GetTop100VotedCharactersRow, error) {
	rows, err := q.db.Query(ctx, getTop100VotedCharacters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTop100VotedCharactersRow
	for rows.Next() {
		var i GetTop100VotedCharactersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Image,
			&i.For,
			&i.Against,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserVoteWithCharacterIds = `-- name: GetUserVoteWithCharacterIds :one
select "userId", "forCharacterId", "againstCharacterId", "dateTime" from "vote" where "userId" = $1 and (("forCharacterId" = $2 and "againstCharacterId" = $3) or ("forCharacterId" = $3 and "againstCharacterId" = $2)) limit 1
`

type GetUserVoteWithCharacterIdsParams struct {
	UserId             string    `json:"userId"`
	ForCharacterId     uuid.UUID `json:"forCharacterId"`
	AgainstCharacterId uuid.UUID `json:"againstCharacterId"`
}

func (q *Queries) GetUserVoteWithCharacterIds(ctx context.Context, arg GetUserVoteWithCharacterIdsParams) (Vote, error) {
	row := q.db.QueryRow(ctx, getUserVoteWithCharacterIds, arg.UserId, arg.ForCharacterId, arg.AgainstCharacterId)
	var i Vote
	err := row.Scan(
		&i.UserId,
		&i.ForCharacterId,
		&i.AgainstCharacterId,
		&i.DateTime,
	)
	return i, err
}

const getUserVotes = `-- name: GetUserVotes :many
select "userId", "forCharacterId", "againstCharacterId", "dateTime" from "vote" where "userId" = $1
`

func (q *Queries) GetUserVotes(ctx context.Context, userid string) ([]Vote, error) {
	rows, err := q.db.Query(ctx, getUserVotes, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vote
	for rows.Next() {
		var i Vote
		if err := rows.Scan(
			&i.UserId,
			&i.ForCharacterId,
			&i.AgainstCharacterId,
			&i.DateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
