// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vote.sql

package repositories

import (
	"context"

	"github.com/google/uuid"
)

const createVote = `-- name: CreateVote :exec
insert into "votes" ("userId", "forCharacterId", "againstCharacterId") values ($1, $2, $3)
`

type CreateVoteParams struct {
	UserId             string    `json:"userId"`
	ForCharacterId     uuid.UUID `json:"forCharacterId"`
	AgainstCharacterId uuid.UUID `json:"againstCharacterId"`
}

func (q *Queries) CreateVote(ctx context.Context, arg CreateVoteParams) error {
	_, err := q.db.Exec(ctx, createVote, arg.UserId, arg.ForCharacterId, arg.AgainstCharacterId)
	return err
}

const getRecent10VotesByUserId = `-- name: GetRecent10VotesByUserId :many
select "userId", "forCharacterId", "againstCharacterId", "dateTime" from "votes" where "userId" = $1 order by "dateTime" desc limit 10
`

func (q *Queries) GetRecent10VotesByUserId(ctx context.Context, userid string) ([]Vote, error) {
	rows, err := q.db.Query(ctx, getRecent10VotesByUserId, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vote
	for rows.Next() {
		var i Vote
		if err := rows.Scan(
			&i.UserId,
			&i.ForCharacterId,
			&i.AgainstCharacterId,
			&i.DateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
